import os
from datetime import datetime
from dotenv import load_dotenv
from fastapi import HTTPException
from google import genai
from google.genai import types

load_dotenv()

GEMINI_MODEL = "gemini-2.5-flash"

BASE_SYSTEM_INSTRUCTION = """You are AlzDx Assistant. You help users understand their cognitive screening results from the Cookie Theft Picture Description task.
The prediction was already generated by the DeBERTa screening model. Never change, recalculate, or reinterpret that prediction.
This is a research screening tool for educational and research purposes. Never provide a medical diagnosis.

CRITICAL RULES:
1. BREVITY: Keep responses concise by default (3–6 sentences, maximum ~120 words unless explicitly asked for more detail).
2. NO REPETITIVE FILLER: NEVER start with filler openings like "Thank you for reaching out," "I understand your curiosity," "Certainly," "I would be happy to," or "Hello there." Jump straight into the direct answer.
3. HIGHLIGHT ACTUAL VALUES: Focus on and bold the patient's specific recorded values (e.g. speech rate, pause count, total pause duration, hesitations, repetitions) instead of reciting the whole generic assessment.
4. FOLLOW-UP CONTINUITY: If the user asks "Why?", "What does that mean?", or a short follow-up, seamlessly continue the previous thought using conversation history without restarting.
5. EXPLAIN LIKE I'M 10: If asked to "Explain like I'm 10" (or ELI10 / simple terms), explain the concept using a simple, relatable everyday analogy in 2–4 sentences.
6. MEDICAL SAFETY: Remind the user that this is a research screening tool and suggest consulting a qualified healthcare professional or neurologist when appropriate."""


def format_patient_context(assessment) -> str:
    created_at = getattr(assessment, "created_at", None)
    if isinstance(created_at, datetime):
        dt_str = created_at.strftime("%Y-%m-%d %H:%M:%S UTC")
    elif created_at:
        dt_str = str(created_at)
    else:
        dt_str = "Not recorded"

    speech_rate = getattr(assessment, "speech_rate", None)
    speech_rate_str = f"{speech_rate:.1f} WPM" if speech_rate is not None else "Unavailable"

    pause_count = getattr(assessment, "pause_count", None)
    pause_count_str = str(pause_count) if pause_count is not None else "Unavailable"

    total_pause = getattr(assessment, "total_pause_seconds", None)
    total_pause_str = f"{total_pause:.2f} seconds" if total_pause is not None else "Unavailable"

    avg_pause = getattr(assessment, "average_pause_seconds", None)
    avg_pause_str = f"{avg_pause:.2f} seconds" if avg_pause is not None else "Unavailable"

    hesitations = getattr(assessment, "hesitation_count", None)
    hesitations_str = str(hesitations) if hesitations is not None else "Unavailable"

    repetitions = getattr(assessment, "repetition_count", None)
    repetitions_str = str(repetitions) if repetitions is not None else "Unavailable"

    confidence = getattr(assessment, "confidence", 0.0)
    try:
        conf_num = float(confidence)
        conf_str = f"{conf_num:.1f}%"
    except (ValueError, TypeError):
        conf_str = str(confidence)

    transcript = (getattr(assessment, "transcript", "") or "").strip() or "No transcript recorded."
    prediction = getattr(assessment, "prediction", "Healthy")

    return f"""
Patient's Specific Assessment Data (Ground Truth):
- Assessment Type: Standardized Cookie Theft Picture Description
- Date Recorded: {dt_str}
- DeBERTa Screening Outcome: {prediction}
- Confidence Score: {conf_str}
- Speech Rate: {speech_rate_str}
- Pause Count: {pause_count_str}
- Total Pause Duration: {total_pause_str}
- Average Pause Duration: {avg_pause_str}
- Hesitations Count: {hesitations_str}
- Repetitions Count: {repetitions_str}
- Recorded Transcript: "{transcript}"
"""


async def query_gemini_assistant(assessment, user_message: str, history: list = None) -> str:
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise HTTPException(
            status_code=503,
            detail="GEMINI_API_KEY environment variable is not configured. Please set it in your environment or .env file.",
        )

    patient_context = format_patient_context(assessment)
    full_system_instruction = f"{BASE_SYSTEM_INSTRUCTION}\n{patient_context}"

    # Build multi-turn content history for conversational memory
    contents = []

    if history:
        # Take the most recent turns (up to 8) to preserve follow-up context
        recent_history = history[-8:]
        for item in recent_history:
            role = getattr(item, "role", None) or (item.get("role") if isinstance(item, dict) else "user")
            content = getattr(item, "content", None) or (item.get("content") if isinstance(item, dict) else "")

            # Skip initial welcome or error messages from history
            if not content or "Hi! I'm the AlzDx Assistant" in content or "Unable to reach" in content:
                continue

            gemini_role = "model" if role in ("assistant", "model") else "user"
            contents.append(
                types.Content(
                    role=gemini_role,
                    parts=[types.Part.from_text(text=content.strip())],
                )
            )

    # Append current user prompt
    contents.append(
        types.Content(
            role="user",
            parts=[types.Part.from_text(text=user_message.strip())],
        )
    )

    try:
        client = genai.Client(api_key=api_key)
        config = types.GenerateContentConfig(
            system_instruction=full_system_instruction,
            temperature=0.3,
            max_output_tokens=350,
        )

        response = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=contents,
            config=config,
        )

        reply = response.text.strip() if response and response.text else ""
        if not reply:
            return "I analyzed your assessment biomarkers, but could not formulate a response. Please ask again."

        # Strip any accidental repetitive openings
        for prefix in [
            "Thank you for reaching out.",
            "Thank you for reaching out!",
            "Thank you for asking.",
            "Thank you for asking!",
            "Certainly!",
            "Certainly.",
            "Sure!",
            "Sure thing!",
        ]:
            if reply.startswith(prefix):
                reply = reply[len(prefix):].strip()

        return reply

    except HTTPException:
        raise
    except Exception as err:
        err_msg = str(err)
        if "API_KEY_INVALID" in err_msg or "invalid api key" in err_msg.lower():
            raise HTTPException(
                status_code=401,
                detail="The configured GEMINI_API_KEY is invalid. Please verify your API key.",
            )
        elif "quota" in err_msg.lower() or "resource_exhausted" in err_msg.lower():
            raise HTTPException(
                status_code=429,
                detail="Gemini API rate limit exceeded. Please try again in a few moments.",
            )
        raise HTTPException(
            status_code=503,
            detail=f"Google Gemini service error: {err_msg}",
        )
