import io
import math
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas


def mm_to_pt(mm: float) -> float:
    return mm * (72.0 / 25.4)


def format_metric(val, suffix=""):
    if val is None or val == "":
        return "Unavailable"
    try:
        f_val = float(val)
        if f_val.is_integer():
            return f"{int(f_val)}{suffix}"
        return f"{f_val:.2f}{suffix}"
    except (ValueError, TypeError):
        return str(val)


def generate_alzdx_pdf_report(assessment) -> bytes:
    """
    Generates a single-page A4 PDF clinical screening report for the given Assessment record.
    Matches all project requirements:
      - Header with AlzDx branding & metadata
      - Screening result with confidence & circular ring
      - Bordered research disclaimer
      - 6 Linguistic analysis metric cards
      - Exact stored transcript
      - Fixed model information
      - Footer: Generated by AlzDx, v1.0, timestamp, Page 1 of 1
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)

    page_width_pt, page_height_pt = A4
    page_width_mm = 210.0
    page_height_mm = 297.0

    margin_left = mm_to_pt(14.0)
    margin_right = mm_to_pt(page_width_mm - 14.0)
    content_width = mm_to_pt(182.0)

    # Coordinate converter: in reportlab (0,0) is bottom-left
    def y_from_top(mm_top: float) -> float:
        return mm_to_pt(page_height_mm - mm_top)

    # Color palette
    c_teal = colors.HexColor("#0d9488")
    c_teal_dark = colors.HexColor("#0f766e")
    c_teal_light = colors.HexColor("#f0fdfa")
    c_teal_border = colors.HexColor("#ccfbf1")
    c_orange = colors.HexColor("#ea580c")
    c_orange_light = colors.HexColor("#fff7ed")
    c_orange_border = colors.HexColor("#fed7aa")
    c_dark = colors.HexColor("#0f172a")
    c_muted = colors.HexColor("#64748b")
    c_card_bg = colors.HexColor("#f8fafc")
    c_card_border = colors.HexColor("#e2e8f0")
    c_white = colors.HexColor("#ffffff")

    # Extract assessment details
    assessment_id = getattr(assessment, "id", "Unassigned")
    id_str = str(assessment_id)
    short_id = f"ALZ-{id_str[:8].upper()}" if len(id_str) > 18 else f"ALZ-{id_str.upper()}"

    prediction = getattr(assessment, "prediction", "Healthy") or "Healthy"
    is_alzheimers = "alzheimer" in prediction.lower()
    prediction_title = "Alzheimer's" if is_alzheimers else "Healthy"

    confidence = float(getattr(assessment, "confidence", 0.0) or 0.0)

    created_at = getattr(assessment, "created_at", None)
    if isinstance(created_at, datetime):
        dt_str = created_at.strftime("%b %d, %Y • %H:%M")
    else:
        dt_str = datetime.now().strftime("%b %d, %Y • %H:%M")

    transcript = (getattr(assessment, "transcript", "") or "").strip() or "No transcript recorded."

    speech_rate = getattr(assessment, "speech_rate", None)
    pause_count = getattr(assessment, "pause_count", None)
    total_pause = getattr(assessment, "total_pause_seconds", None)
    avg_pause = getattr(assessment, "average_pause_seconds", None)
    hesitations = getattr(assessment, "hesitation_count", None)
    repetitions = getattr(assessment, "repetition_count", None)

    # ==========================================
    # 1. HEADER (mm 12 to 32)
    # ==========================================
    header_top = 12.0
    logo_size = mm_to_pt(13.0)
    logo_x = margin_left
    logo_y = y_from_top(header_top + 13.0)

    # Logo badge
    c.setFillColor(c_teal)
    c.roundRect(logo_x, logo_y, logo_size, logo_size, 7.0, fill=1, stroke=0)

    # Brain / Dx Mark on Logo
    c.setFillColor(c_white)
    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(logo_x + logo_size / 2.0, logo_y + logo_size / 2.0 - 4.0, "Dx")

    # Header Title
    title_x = logo_x + logo_size + mm_to_pt(3.5)
    c.setFillColor(c_dark)
    c.setFont("Helvetica-Bold", 15)
    c.drawString(title_x, y_from_top(header_top + 5.5), "AlzDx – Cognitive Screening Report")

    # Assessment Type Tag
    tag_w = mm_to_pt(60.0)
    tag_h = mm_to_pt(5.2)
    tag_y = y_from_top(header_top + 13.0)
    c.setFillColor(c_teal_light)
    c.setStrokeColor(c_teal_border)
    c.setLineWidth(0.8)
    c.roundRect(title_x, tag_y, tag_w, tag_h, 3.0, fill=1, stroke=1)

    c.setFillColor(c_teal_dark)
    c.setFont("Helvetica-Bold", 7.5)
    c.drawString(title_x + mm_to_pt(2.5), tag_y + mm_to_pt(1.5), "Cookie Theft Picture Description")

    # Header Right Metadata
    c.setFillColor(c_dark)
    c.setFont("Helvetica-Bold", 8.2)
    c.drawRightString(margin_right, y_from_top(header_top + 4.5), f"Report ID: {short_id}")

    c.setFillColor(c_muted)
    c.setFont("Helvetica", 7.5)
    c.drawRightString(margin_right, y_from_top(header_top + 9.5), f"Date & Time: {dt_str}")

    # Two-tone accent bar (Teal + Orange)
    bar_y = y_from_top(header_top + 16.5)
    c.setFillColor(c_teal)
    c.rect(margin_left, bar_y, content_width * 0.65, mm_to_pt(1.0), fill=1, stroke=0)
    c.setFillColor(c_orange)
    c.rect(margin_left + content_width * 0.65, bar_y, content_width * 0.35, mm_to_pt(1.0), fill=1, stroke=0)

    # ==========================================
    # 2. SCREENING RESULT HERO CARD (mm 33 to 71)
    # ==========================================
    card_top = 33.0
    card_h = mm_to_pt(38.0)
    card_y = y_from_top(card_top + 38.0)

    c.setFillColor(c_card_bg)
    c.setStrokeColor(c_card_border)
    c.setLineWidth(1.0)
    c.roundRect(margin_left, card_y, content_width, card_h, 8.0, fill=1, stroke=1)

    # Accent left indicator stripe
    stripe_w = mm_to_pt(3.2)
    stripe_color = c_orange if is_alzheimers else c_teal
    c.setFillColor(stripe_color)
    c.roundRect(margin_left, card_y, stripe_w, card_h, 4.0, fill=1, stroke=0)

    # Pill badge: Screening Outcome
    badge_x = margin_left + mm_to_pt(7.0)
    badge_y = y_from_top(card_top + 9.2)
    badge_w = mm_to_pt(34.0)
    badge_h = mm_to_pt(4.8)
    badge_bg = c_orange_light if is_alzheimers else c_teal_light
    badge_bdr = c_orange_border if is_alzheimers else c_teal_border
    badge_txt = c_orange if is_alzheimers else c_teal_dark

    c.setFillColor(badge_bg)
    c.setStrokeColor(badge_bdr)
    c.setLineWidth(0.8)
    c.roundRect(badge_x, badge_y, badge_w, badge_h, 3.0, fill=1, stroke=1)

    c.setFillColor(badge_txt)
    c.setFont("Helvetica-Bold", 6.8)
    c.drawCentredString(badge_x + badge_w / 2.0, badge_y + mm_to_pt(1.4), "SCREENING RESULT")

    # Prediction Text
    c.setFillColor(stripe_color)
    c.setFont("Helvetica-Bold", 21)
    c.drawString(badge_x, y_from_top(card_top + 18.5), prediction_title)

    # Summary copy
    c.setFillColor(c_muted)
    c.setFont("Helvetica", 8.2)
    copy_text = (
        "Acoustic and semantic indicators show patterns associated with cognitive decline."
        if is_alzheimers
        else "Speech fluency, pause dynamics, and lexical markers indicate typical cognitive patterns."
    )
    c.drawString(badge_x, y_from_top(card_top + 24.5), copy_text)

    c.setFont("Helvetica", 7.2)
    c.setFillColor(colors.HexColor("#94a3b8"))
    c.drawString(badge_x, y_from_top(card_top + 31.5), f"Assessment UID: {id_str}")

    # Circular Confidence Ring (Right Side)
    ring_dia = mm_to_pt(30.0)
    ring_center_x = margin_right - mm_to_pt(19.0)
    ring_center_y = card_y + card_h / 2.0

    # Background circle
    c.setStrokeColor(colors.HexColor("#e6efec"))
    c.setLineWidth(5.5)
    c.circle(ring_center_x, ring_center_y, ring_dia / 2.0 - 3.0, stroke=1, fill=0)

    # Confidence arc (approximated with highlighted segment)
    c.setStrokeColor(stripe_color)
    c.setLineWidth(5.5)
    clamped_conf = max(0.0, min(100.0, confidence))
    extent = (clamped_conf / 100.0) * 360.0
    c.arc(
        ring_center_x - (ring_dia / 2.0 - 3.0),
        ring_center_y - (ring_dia / 2.0 - 3.0),
        ring_center_x + (ring_dia / 2.0 - 3.0),
        ring_center_y + (ring_dia / 2.0 - 3.0),
        90.0,
        -extent,
    )

    # Center text in ring
    c.setFillColor(c_dark)
    c.setFont("Helvetica-Bold", 13.5)
    c.drawCentredString(ring_center_x, ring_center_y - 2.0, f"{clamped_conf:.1f}%")

    c.setFillColor(c_muted)
    c.setFont("Helvetica", 6.8)
    c.drawCentredString(ring_center_x, ring_center_y - 10.0, "confidence")

    # ==========================================
    # 3. RESEARCH DISCLAIMER CALLOUT (mm 74 to 86)
    # ==========================================
    disc_top = 74.0
    disc_h = mm_to_pt(12.0)
    disc_y = y_from_top(disc_top + 12.0)

    c.setFillColor(c_orange_light)
    c.setStrokeColor(c_orange_border)
    c.setLineWidth(0.8)
    c.roundRect(margin_left, disc_y, content_width, disc_h, 6.0, fill=1, stroke=1)

    c.setFillColor(c_orange)
    c.roundRect(margin_left, disc_y, mm_to_pt(2.2), disc_h, 3.0, fill=1, stroke=0)

    c.setFillColor(colors.HexColor("#c2410c"))
    c.setFont("Helvetica-Bold", 7.5)
    c.drawString(margin_left + mm_to_pt(6.0), y_from_top(disc_top + 4.8), "RESEARCH DISCLAIMER:")

    c.setFont("Helvetica", 7.2)
    c.setFillColor(colors.HexColor("#9a3412"))
    c.drawString(
        margin_left + mm_to_pt(43.0),
        y_from_top(disc_top + 4.8),
        "This report is generated by the AlzDx research screening system for educational and research purposes and is not a medical diagnosis.",
    )

    c.setFont("Helvetica", 6.8)
    c.setFillColor(colors.HexColor("#b45309"))
    c.drawString(
        margin_left + mm_to_pt(6.0),
        y_from_top(disc_top + 9.0),
        "Results must be interpreted in conjunction with formal neuropsychological batteries and clinical neurological evaluation.",
    )

    # ==========================================
    # 4. LINGUISTIC ANALYSIS (mm 89 to 134)
    # ==========================================
    ling_top = 89.0
    c.setFillColor(c_dark)
    c.setFont("Helvetica-Bold", 9.5)
    c.drawString(margin_left, y_from_top(ling_top + 2.0), "Linguistic & Temporal Biomarkers")

    c.setFont("Helvetica", 7.0)
    c.setFillColor(c_muted)
    c.drawString(
        margin_left + mm_to_pt(68.0),
        y_from_top(ling_top + 2.0),
        "Derived from acoustic segmentation & speech timing analysis",
    )

    metric_defs = [
        ("Speech Rate", format_metric(speech_rate, " WPM")),
        ("Pause Count", format_metric(pause_count, "")),
        ("Total Pause Duration", format_metric(total_pause, " s")),
        ("Average Pause Duration", format_metric(avg_pause, " s")),
        ("Hesitations", format_metric(hesitations, "")),
        ("Repetitions", format_metric(repetitions, "")),
    ]

    col_gap = mm_to_pt(3.0)
    row_gap = mm_to_pt(2.5)
    col_w = (content_width - (col_gap * 2.0)) / 3.0
    card_row_h = mm_to_pt(13.5)
    grid_top_mm = ling_top + 4.5

    for idx, (label, val) in enumerate(metric_defs):
        col = idx % 3
        row = idx // 3
        mx = margin_left + col * (col_w + col_gap)
        my = y_from_top(grid_top_mm + (row + 1) * 13.5 + row * 2.5)

        c.setFillColor(c_card_bg)
        c.setStrokeColor(c_card_border)
        c.setLineWidth(0.8)
        c.roundRect(mx, my, col_w, card_row_h, 5.0, fill=1, stroke=1)

        # Little teal indicator
        c.setFillColor(c_teal)
        c.circle(mx + mm_to_pt(4.0), my + card_row_h - mm_to_pt(4.2), mm_to_pt(1.0), fill=1, stroke=0)

        # Label
        c.setFont("Helvetica-Bold", 6.8)
        c.setFillColor(c_muted)
        c.drawString(mx + mm_to_pt(7.0), my + card_row_h - mm_to_pt(5.0), label.upper())

        # Value
        c.setFont("Helvetica-Bold", 10.5)
        c.setFillColor(c_dark)
        c.drawString(mx + mm_to_pt(7.0), my + mm_to_pt(3.5), val)

    # ==========================================
    # 5. ASSESSMENT TRANSCRIPT (mm 138 to 198)
    # ==========================================
    trans_top = 138.0
    c.setFillColor(c_dark)
    c.setFont("Helvetica-Bold", 9.5)
    c.drawString(margin_left, y_from_top(trans_top + 2.0), "Assessment Transcript")

    c.setFont("Helvetica", 7.0)
    c.setFillColor(c_muted)
    c.drawString(
        margin_left + mm_to_pt(48.0),
        y_from_top(trans_top + 2.0),
        "Exact transcript evaluated by model (verbatim with punctuation preserved)",
    )

    box_h = mm_to_pt(46.0)
    box_y = y_from_top(trans_top + 4.5 + 46.0)
    c.setFillColor(c_card_bg)
    c.setStrokeColor(c_card_border)
    c.setLineWidth(0.8)
    c.roundRect(margin_left, box_y, content_width, box_h, 6.0, fill=1, stroke=1)

    # Word wrap transcript
    text_object = c.beginText(margin_left + mm_to_pt(5.0), box_y + box_h - mm_to_pt(6.0))
    text_object.setFont("Helvetica", 7.8)
    text_object.setFillColor(c_dark)
    text_object.setLeading(11.0)

    words = transcript.split()
    current_line = []
    line_limit = 11
    rendered_lines = 0

    for word in words:
        current_line.append(word)
        test_line = " ".join(current_line)
        if c.stringWidth(test_line, "Helvetica", 7.8) > (content_width - mm_to_pt(10.0)):
            current_line.pop()
            text_object.textLine(" ".join(current_line))
            rendered_lines += 1
            if rendered_lines >= line_limit:
                text_object.textLine("...")
                break
            current_line = [word]

    if current_line and rendered_lines < line_limit:
        text_object.textLine(" ".join(current_line))

    c.drawText(text_object)

    # ==========================================
    # 6. MODEL INFORMATION (mm 202 to 226)
    # ==========================================
    model_top = 202.0
    c.setFillColor(c_dark)
    c.setFont("Helvetica-Bold", 9.5)
    c.drawString(margin_left, y_from_top(model_top + 2.0), "Deep Learning Model Information")

    m_box_h = mm_to_pt(19.0)
    m_box_y = y_from_top(model_top + 4.5 + 19.0)
    c.setFillColor(c_card_bg)
    c.setStrokeColor(c_card_border)
    c.setLineWidth(0.8)
    c.roundRect(margin_left, m_box_y, content_width, m_box_h, 6.0, fill=1, stroke=1)

    model_cols = [
        ("BASE MODEL", "microsoft/deberta-v3-base", False),
        ("ARCHITECTURE", "Attention Pooling + Mean Pooling", False),
        ("CHECKPOINT", "checkpoint-264", False),
        ("FINAL TEST ACCURACY", "89.33%", True),
    ]

    m_col_w = content_width / 4.0
    for idx, (label, val, is_hl) in enumerate(model_cols):
        mx = margin_left + idx * m_col_w + mm_to_pt(4.0)

        c.setFont("Helvetica-Bold", 6.4)
        c.setFillColor(c_muted)
        c.drawString(mx, m_box_y + m_box_h - mm_to_pt(5.5), label)

        if is_hl:
            c.setFont("Helvetica-Bold", 11.0)
            c.setFillColor(c_teal_dark)
            c.drawString(mx, m_box_y + mm_to_pt(4.5), val)
        else:
            c.setFont("Helvetica-Bold", 7.6)
            c.setFillColor(c_dark)
            c.drawString(mx, m_box_y + mm_to_pt(5.0), val)

        if idx < 3:
            div_x = margin_left + (idx + 1) * m_col_w
            c.setStrokeColor(c_card_border)
            c.setLineWidth(0.5)
            c.line(div_x, m_box_y + mm_to_pt(3.0), div_x, m_box_y + m_box_h - mm_to_pt(3.0))

    # ==========================================
    # 7. FOOTER (mm 230 to 242)
    # ==========================================
    footer_line_y = y_from_top(231.0)
    c.setStrokeColor(c_card_border)
    c.setLineWidth(0.8)
    c.line(margin_left, footer_line_y, margin_right, footer_line_y)

    footer_text_y = y_from_top(236.0)
    c.setFont("Helvetica-Bold", 7.2)
    c.setFillColor(c_dark)
    c.drawString(margin_left, footer_text_y, "Generated by AlzDx")

    c.setFont("Helvetica", 6.8)
    c.setFillColor(c_muted)
    c.drawString(
        margin_left + mm_to_pt(32.0),
        footer_text_y,
        f"Project Version: v1.0   •   Generated On: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
    )

    c.setFont("Helvetica-Bold", 7.2)
    c.drawRightString(margin_right, footer_text_y, "Page 1 of 1")

    # Finalize & Save page
    c.showPage()
    c.save()

    return buffer.getvalue()
